version: '3.9'

services:
  app:
    image: trants/docker-nginx:1.21
    ports:
      - '3000:8000'
      - '8443:8443'
    volumes:
      - ../build/:/var/www:cached
      - ./docker/nginx/sites-enabled:/etc/nginx/conf.d
      - sockdata:/sock
      - ssldata:/etc/nginx/certs

volumes:
  sockdata:
  ssldata:
